stages:
  - test
  - deploy

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

check_pkg:
  stage: test
  image: "bioconductor/bioconductor_docker:RELEASE_3_15"
  script:
    - R -e 'remotes::install_cran("BiocManager")'
    - R -e 'remotes::install_deps(dependencies = TRUE)'
    - R -e 'devtools::check()'

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

build_site_and_coverage:
  stage: test
  image: "bioconductor/bioconductor_docker:RELEASE_3_15"
  only:
    - master
  script:
    - R -e 'remotes::install_cran("BiocManager")'
    - R -e 'remotes::install_local(force = TRUE, dependencies = TRUE)'
    - R -e 'remotes::install_cran("covr")'
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::gitlab(quiet = FALSE)'
  artifacts:
    paths:
      - public
    expire_in: 30 days


pages:
  stage: deploy
  image: alpine
  script:
    - ls
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
    - master
