stages:
  - check
  - build_website
  - deploy


# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

check_pkg:
  stage: check
  image: "bioconductor/bioconductor_docker:RELEASE_3_15"
  tags:
    - sipss
  before_script:
    - apt-get update
    - apt-get install -y qpdf ghostscript texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - Rscript -e 'remotes::install_cran(c("rcmdcheck", "BiocManager"))'
  script:
    - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
    - Rscript -e 'rcmdcheck::rcmdcheck()'

BiocCheck:
  stage: check
  image: "bioconductor/bioconductor_docker:RELEASE_3_15"
  tags:
    - sipss
  before_script:
    - Rscript -e 'BiocManager::install("BiocCheck")'
  script:
    - Rscript -e 'BiocCheck::BiocCheck(`quit-with-status` = TRUE, `no-check-R-ver` = TRUE, `no-check-bioc-help` = TRUE)'
  allow_failure: true


# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

build_site_and_coverage:
  stage: build_website
  image: "bioconductor/bioconductor_docker:RELEASE_3_15"
  tags:
    - sipss
  only:
    - master
  before_script:
    - apt-get update
    - apt-get install -y qpdf ghostscript texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - Rscript -e 'remotes::install_cran("BiocManager")'
    - Rscript -e 'remotes::install_cran(c("covr", "pkgdown"))'
  script:
    - Rscript -e 'remotes::install_local(force = TRUE, dependencies = TRUE)'
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::gitlab(quiet = FALSE)'
  artifacts:
    paths:
      - public
    expire_in: 30 days


pages:
  stage: deploy
  image: alpine
  script:
    - ls
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
    - master
